[project]
name = "03-order-agent"
version = "0.1.0"
description = "餐厅点餐智能助手,基于 LangChain 实现自然语言查询菜品"
# readme = "README.md"
authors = [
    { name = "Your Name", email = "your.email@example.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "langchain>=1.4.0",
    "langchain-huggingface>=1.2.2",
    "langchain-mcp-adapters>=0.3.2",
    "langchain-openai>=1.6.1",
    "langgraph-checkpoint-postgres>=3.1.2",
    "psycopg[binary]>=3.3.5",
    "pymilvus>=3.0.1",
    "pymysql>=1.2.0",
    "python-dotenv>=1.2.3",
    "redis>=8.1.0",
    "sentence-transformers>=6.0.1",
]
